Spring:
  h2:
    console:
      enabled: true
  datasource:

    url: jdbc:h2:./appdb
    password:
    username: sa

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true



  profiles:
    active: dev
server:
  port: 9090
